cl#### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ####
deployment:
  tasks:
    - export DEPLOYPATH=/home/editcezo/repositories/editedge
    - cd $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH  # Copy all files
    - npm install --production   # Install dependencies
    - pm2 restart server.js      # Restart Node.js app
